dist: xenial
sudo: false
latex: false

language: r

r: 
  - release

r_packages:
  - rsconnect
  - shiny
  - shinydashboard
  - DT
  - readxl
  - magrittr
  - dplyr
  - tidyr
  - data.table
  - mltools
  - summarytools
  - ROCR
  - purrr
  - e1071
  - stringr
  - rpart
  - rpart.plot
  - glmnet
  - randomForest
  - fastDummies
  - ggplot2

apt_packages:
  - libgdal-dev
  - libudunits2-dev
  - libmagick++-dev

warnings_are_errors: false

cache:
  packages: true

script:
  - R -f deploy.R